### ISSUE TITLE
Further OpenServerList Cleanup

### ISSUE THREAD

**Issue by ijemafe** [OpenRVS-devs/OpenRVS#23]
There is some additional cleanup we can perform in OpenServerList.uc. Wanted to put this in a new issue instead of adding to the existing PR.

There are three improvements I think we can make:
1. ParseServersINI and ServerListSuccess have a lot of parsing overlap. Merge these two into ParseServersINI.
2. Replace ServerListSuccess with a function which operates on `array<Server>` instead of `array<string>`. This way it can accept data from INI or CSV.
3. Move all access to OpenMultiPlayerWidget into a final function that is called with the completed server list (after loading INI, CSV, or local file) to deduplicate the widget calls

In case that's unclear, this is the flow I am picturing:

functions:
```
Init() -> void
ParseServers(HttpRequest) -> array<Server>
- calls ParseServersCSV(HttpRequest) -> array<Server>
- falls back to ParseServersINI(HttpRequest) -> array<Server>
- falls back to LoadFallbackServers() -> array<Server>
RegisterServers(array<Server>) -> void
```

**Comment by rvstwi** [comment]
Perfectly clear, and a logical next step for integrating CSV support (#3 )

**Comment by rvstwi** [comment]
Comments in this class need cleaning up too since they're already behind the current state of parsing.  EG
//strips out extra info on the ends of the string and returns a server string in this format:
//a server name",IP="44.434.4.434:7777",Locked=false,GameMode="Adver
is no longer how ParseServersINI() works.
