### ISSUE TITLE
Internet servers appearing in LAN tab

### ISSUE THREAD

**Issue by rvstwi** [OpenRVS-devs/OpenRVS#29]
A handful of internet servers have always appeared in the LAN tab, but as I improved ping/sorting in Internet tab, it appears that all the internet servers now like to appear in LAN.  (Related issue: #21 )

**Comment by rvstwi** [comment]
Looks to me like an issue we introduced when trying to prevent the game from querying servers so much.  We commented out
Refresh( FALSE );
in function ManageTabSelection().  This originally would handle removing internet servers from the list and adding LAN servers when changing from internet tab to lan tab.

When I'm done with update for issue #21 I will work on uncommenting that line and making sure it works as anticipated.

**Comment by ijemafe** [comment]
This may be something else. If you click back and forth between INTERNET SERVER and LAN SERVER, you'll get 0-1 servers in the LAN list (currently the 24/7 Deathmatch server).

However, if you click on any other server on the INTERNET SERVER tab before switching to the LAN SERVER tab, it will never appear.

**Comment by ijemafe** [comment]
While the merged PR does prevent the exact issue from occurring, I think we may have masked the root cause:

1. A user on the Tactical Gaming Discord server had the same bug on OpenRVS 1.4, indicating that it's not a bug we introduced since moving to Github: https://discordapp.com/channels/260385890017214465/331387031110549506/714720425346596914
2. The code we commented out said `if ( m_LanServers.m_GameServerList.length == 0 )`, which should not have been in play since there was 1 server in the LAN list.
