### ISSUE TITLE
Feature Request - Ubi UserName & Password for N4Admin

### ISSUE THREAD

**Issue by Dateranoth** [OpenRVS-devs/OpenRVS#46]
First, let me start by thanking you both for keeping Raven Shield alive! I'm happy to come back to it after all this time and see it's still possible to connect and play.

I see with your modifications, the client no longer sends an UBI ID. I have been keeping my personal copy of N4Admin going, and I need the usernames to properly write statistics.  I recently, as in just now, branched off a copy of N4Admin on GitHub, and pushed all [my changes](https://github.com/Dateranoth/RainbowSix-Ravenshield-N4Admin). I have made changes to make the php code work with PHP 7 and recently added some code in hopes of making it work with OpenRVS. You can see my long standing running copy [here at dateranoth.com ](https://dateranoth.com/rvsstatsmain.html)

I made my own changes to test this out with OpenRVS (they worked), and I was hoping you could implement something similar in your base code. Basically, my idea is to have OpenRVS push a Username_Password as one string to the server using the SetUbiAccount. This UBI Name_Pass, is then sent to the N4Admin stats site using the code originally provided by that team. Once it is posted, it is parsed, checked against the database, and then the stats are recorded to the proper user if the password matches. If no match, the data is recorded to the Anonymous user along with their nickname.

This is achieved with the below code, and the client using the INI file to pass along their name.

```
//fools the UBI ID window into thinking you successfully logged in
//so you can select the Internet tab without any problems
//installed client side
class OpenUbiLogIn extends R6WindowUbiLogIn;

//in 1.56 this is done in function Manager()
//changed in 1.6 to processgsmsg


//N4Admin stats server uses UBI ID to identify players.
//This modifications will allow a player to set a username_uniquekey
//This will then be seperated web server side to allow for unique user accounts
var config string N4User_Pass;//Username_UniqueKey

function ProcessGSMsg (string _szMsg)
{
	m_pR6UbiAccount.HideWindow();
	m_pDisconnected.HideWindow();
	HideWindow();
    m_GameService.SetUbiAccount( N4User_Pass, "1234" ); //N4Admin doesn't use the password field. Just entering something because I'm not sure if I need it or not.
    m_GameService.m_bUbiAccntInfoEntered = TRUE;
	m_GameService.SaveConfig();
	m_pSendMessageDest.SendMessage(MWM_UBI_LOGIN_SUCCESS);
	class'OpenLogger'.static.Debug("SUCCESSFULLY FAKED UBI LOGIN", self);
}

defaultproperties
{
	N4User_Pass="Anonymous_Pass" //Default will log all users to same Anonymous account. This includes users without password string, and without this mod.
}
```

```
[OpenRVS.OpenUbiLogIn]
N4User_Pass=Anonymous_Pass
```

Thanks again!

**Comment by ijemafe** [comment]
Hey, thanks for the message!

We no longer send the Ubi ID because [the SDK used to send it](https://github.com/ijemafe/raven-shield-1.56/blob/19bed4d29d2f712df7b7ead226653712410204df/R6Window/Classes/R6WindowUbiLogIn.uc#L198L200) no longer works at all, unfortunately, due to the backend being shut down.

That said, we do have an HTTP 1.0 client capable of sending GET requests (could be extended with POST/PUT if necessary), and also the ability to send UDP traffic. Which protocols does N4Admin support currently?

In terms of security, what is being locked behind a password? Would username-based tracking be sufficient?

Regarding sending the password over the Internet, it might be better to hash the password on both ends (client and server), transmit the hash over the Internet, and compare hashes on the backend. We would have to implement a hash algorithm for this, but it should be possible. Note that we don't have the ability to encrypt any Internet traffic with SSL, as we can't read the certificates from local disk.

Question for @rvstwi: should this be part of OpenRVS or part of a client mod? I'm not familiar enough with mods myself to know for sure.

**Comment by Dateranoth** [comment]
By modifying OpenUbiLogIn.uc with the code I listed above, and then compiling I was able to get the client to send my username-pass string to the server. If you don’t think it belongs in OpenRVS I completely understand. I haven’t tried extending the class with my own mod. I am not familiar with this code, and I don’t know how the precedence works.

Ideally this should be secured, but I was trying to work around N4Admin without making any major code changes since the original game server side mod source is not available anywhere that I know of. Not much is secure about any part of N4Admin.

In this case, I don’t think it’s too important, as all it  protects is the clients stats on the N4Admin server. Even then it only protects another user from recording their stats to the same id. Username based tracking would be sufficient, but it would be too easy for accidental overlap of names or intentional trolling. The password is a way to claim your username on that server. Provided it hasn’t been taken already.

I don’t know all the protocols N4Admin is using. I haven’t dug through all the decompiled code yet. I just spent some time using it to debug and figure out how to disable the post to their old master server that is long dead.

The way it was coded was to take the Ubi ID which it pulled from the game engine, and post it along with stats to the web server via a PHP http 1.0 post after each round. 

All of this still works (had to open the post.php to allow none ssl) but without the Ubi ID, there is no unique identifier to assign the data.  This is where the user_pass comes into play. 

Thanks for taking the time to respond. If it’s outside the scope I fully understand. I can keep a branch off your master for my use if necessary.

**Comment by rvstwi** [comment]
I think that OpenRVS is a good candidate to put something like this in @ijemafe because I've already had to ensure compatibility with N4Admin in the past (class OpenBeacon) and because a separate mod to do this may clash with OpenRVS's UBI login skip functionality.

@Dateranoth Rather than just assigning anyone without a username the "anonymous" label, why not pregenerate a pseudo-random string identifier for each player?  The chances of two identical usernames being generated are basically nil.  That identifier could then be used on the N4Admin side of things.

Some notes: SetUbiAccount() just sets the variables m_szUserID and m_szSavedPwd in Ravenshield.ini.  The password var of course stays private but the m_szUserID is visible to anyone on the server who knows what they're doing.  @Dateranoth This means that if you store the name and password both in this variable, anyone with the ability to compile a small amount of code could have others' passwords visible to them.  I think we either forget about a password entirely or we come up with a different way to secure it.

**Comment by Dateranoth** [comment]
@rvstwi 
The random identifier would work for round to round matches, but there still would be no way to associate long term data without the unique identifier.

Is there anyway we could build this into OpenRVS?  Use the existing interface to have the client send username and password, set in a variable client side. Then store that server side. If the client ID doesn’t exist, it is added. If it does, the if is checked against the stored password. A match keeps the provided UBI/User name from client. Mismatch changes UBI/User name to Anonymous? Ideally with a notification to the user.

I can dig into this idea some of you think it’s possible.

**Comment by rvstwi** [comment]
I think that is possible @Dateranoth .  Why wouldn't a randomly generated identifier work for repeat clients?  We check if m_szUserID is "", and if so generate a unique one.  That gets saved in Ravenshield.ini, so unless they manually find it in their INI file and modify, it would persist between multiple times they play the game.

**Comment by Dateranoth** [comment]
@rvstwi 

It comes back to N4Admin. The UserID sent to the server is sent to the web server. That is what the user needs to find their personal stats. It’s also open to the public, so anyone could easily find it and then copy it. N4Admin was built around the assumption UbiID was unique and Ubisoft did all the account verification.

**Comment by rvstwi** [comment]
Fair enough good point.  We'll have to explore some ways to make the process secure.

**Comment by Dateranoth** [comment]
So, I've been looking at this, and I have some ideas. I don't think anything is perfect, but I was hoping we could use the m_szAuthorizationID field. This is passed to the server with the PlayerID, but what I'm not sure of, is if it is accessible to other players or not. Either way we could hash/salt it server side, and store the hash and salt on the server. Upon connection, immediately verify the Username and AuthID against the stored information. Then, either clear the field from the player information, or insert a random ID.

I could play around with this, but I'm not very familiar with what is available in the game code. Is there any SHA256 or other hashing functions available? Is there an easy way to write and read a list of PlayerIDs, Hash, and Salt?

**Comment by Dateranoth** [comment]
@rvstwi 

So, I’ve managed to get the client to send a new n4pass option to the join server string. 

I’ve been trying to extend the AccessControl class to parse the options. For now, I was simply trying to log the data as a test. 

I can get the code to compile with an override to PreLogin, but I cannot seem to get the server to load the changed class.

I’ve tried changing Engine.GameInfo AccesControlClass. This seems to do nothing. If I add it to serveractors I get an error about not being able to find the class.

Could you help point me in the right direction? Am I approaching this wrong?

Thanks.

**Comment by Dateranoth** [comment]
Going to close this out. Been working with @rvstwi on Discord, and he wrote up a mod that puts me in the (extremely) right direction. I will implement this mod alongside the current N4 branch I'm working on. The end goal will be to allow N4 to work with OpenRVS without needing to change anything here. Thanks for all the help!
